<?xml version="1.0" encoding="UTF-8"?>
<MobileElementEntity>
   <description></description>
   <name>button-profile</name>
   <tag></tag>
   <elementGuidId>d030512f-172f-49bb-b26e-5765732571b3</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//android.widget.FrameLayout[@content-desc=&quot;Profile&quot;]/android.view.ViewGroup/android.widget.TextView</value>
      <webElementGuid>24cc7bd2-8c3e-45b8-aff9-330b477eb358</webElementGuid>
   </webElementProperties>
   <locator>//android.widget.FrameLayout[@content-desc=&quot;Profile&quot;]/android.view.ViewGroup/android.widget.TextView</locator>
   <locatorStrategy>ATTRIBUTES</locatorStrategy>
</MobileElementEntity>
